# Macine Learning Zoomcamp
## 1.7 Introduction to Numpy

Content:
- Create Arrays
- Multi-dimentional arrays
- Randomly generated arrays
- Element-wise operations
  - Comparison operations
  - Logical Operations
- Summarizing operations

In [1]:
 import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

# Creating arrays

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [15]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [17]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [21]:
 np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimensional arrays

In [27]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
n = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
# 0  [1,2,3]
# 1  [4,5,6]
# 2  [7,8,9]
#    0  1  2

n[0,1] = 20
# row 0 column 1
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [50]:
# Access/change rows
n[2] = [1,1,1]
# Second row
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [61]:
# Access/change columns
n[:,2] = [0,1,2]
# Last column
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

# Randomly generated arrays

In [68]:
# (rows, columns) not really random, generated by seed, can give a sequence picking a seed
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [70]:
# .randn - normal
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [74]:
# integers by 10 or 100 multiplu the element 
# 100 * np.random.randn(5,2) or use a function for random integers
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [77]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [90]:
# to add a number
# a + 1
# multiply every element by 2
# a * 2
# can combine operations
b = (10 + (a*2))** 2/100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [95]:
# add two arrays
# a+b
# mutiply, divide, etc
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

# Comparison operations

In [99]:
a >= 2

array([False, False,  True,  True,  True])

In [103]:
a

array([0, 1, 2, 3, 4])

In [105]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [106]:
a > b

array([False, False,  True,  True,  True])

In [110]:
# Return the elements of an array in which the condition is TRUE a[condition]
a[a > b]

array([2, 3, 4])

# Summarizing operations

In [111]:
# Return a number
a.min()

np.int64(0)

In [113]:
a.max()

np.int64(4)

In [114]:
a.sum()

np.int64(10)

In [115]:
a.mean()

np.float64(2.0)

In [116]:
a.std()

np.float64(1.4142135623730951)

In [119]:
# work for multi-dimensional arrays
n.sum()

np.int64(35)

In [120]:
n.min()

np.int64(0)

In [125]:
n.max()

np.int64(20)