# Machine Learning Zoomcamp
## 1.8 Linear algebra refresher

Content:
- Vector operations
- Multiplications
  - Vector-vector
  - Matrix-vector
  - Matrix-matrix
- Identify matrix
- Inverse

In [1]:
import numpy as np

In [7]:
u = np.array([2,4,5,6])
2 * u

array([ 4,  8, 10, 12])

In [8]:
v = np.array([1,0,0,2])
u + v

array([3, 4, 5, 8])

In [9]:
u * v

array([ 2,  0,  0, 12])

 ## Multiplication

In [13]:
# .shape gives us the size
v.shape

(4,)

In [14]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [15]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [16]:
# this replaces the function, vector-vector multiplication
u.dot(v)

np.int64(14)